spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/collab_workspace
    username: collab
    password: collab
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: valkey
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/collab-cloud
          jwk-set-uri: http://keycloak:8080/realms/collab-cloud/protocol/openid-connect/certs