spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/collab_workspace
    username: collab
    password: collab

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration